General questions

Which is the only body part that is fully grown from birth?
answer = 'Eyes'
In what country was Elon Musk born 
answer = 'South Africa'
How many hearts does an octopus have?
answer '3'
What planet is closest to the sun? 
answer 'Mercury'
What is a group of crows called?
answer 'A murder'



Geography

What is the name of the tallest mountain in the world?
Answer:  Mount Everest 
Alternatives: 'K2' 'Lhotse' 'Makalu'

Which country has the largest population in the world?
Answer: China
Alternatives: 'India' 'USA' 'Russia'

Where are the Spanish Steps located?
Answer: Rome, Italy
Alternatives: 'Madrid, Spain' 'Bogota, Colombia' 'Quito, Ecuador'

What countries border directly north of Hungary?
Answer: Ukraine, Serbia
Alternatives: 'Turkey' 'Switzerland'

What season does Australia experience in December?
Answer:  Summer 
Alternatives: 'Winter' 'Spring' 'Fall'


Computer

What do you call a portable computer?
Answer: Laptop

What do you use to read CDs/DVDs?
Answer: Cd and DvD player

What memory below is the largest?
Answer: 1TB
Alternatives: '1GB' '55000Bytes' '10GB'

You need an internet browser to access the Internet. (True/False)
Answer: True

A software comes with a product key.(True/False)
Answer: True